// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"

	"github.com/google/uuid"
)

type Cage struct {
	ID     uuid.UUID
	Name   sql.NullString
	Status sql.NullInt32
}

type Dinosaur struct {
	ID          uuid.UUID
	Name        sql.NullString
	EatingHabit sql.NullInt32
	Species     sql.NullInt32
	CageID      uuid.NullUUID
}
