// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package postgres

import (
	"context"
	"database/sql"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			DeleteDinosaurFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteDinosaur method")
//			},
//			GetCageFunc: func(ctx context.Context, id uuid.UUID) (Cage, error) {
//				panic("mock out the GetCage method")
//			},
//			GetCagesFunc: func(ctx context.Context) ([]Cage, error) {
//				panic("mock out the GetCages method")
//			},
//			GetDinosaurFunc: func(ctx context.Context, id uuid.UUID) (Dinosaur, error) {
//				panic("mock out the GetDinosaur method")
//			},
//			GetDinosaurByNameFunc: func(ctx context.Context, name sql.NullString) (Dinosaur, error) {
//				panic("mock out the GetDinosaurByName method")
//			},
//			GetDinosaursFunc: func(ctx context.Context) ([]Dinosaur, error) {
//				panic("mock out the GetDinosaurs method")
//			},
//			GetDinosaursByCageFunc: func(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error) {
//				panic("mock out the GetDinosaursByCage method")
//			},
//			UpdateCageStatusFunc: func(ctx context.Context, arg UpdateCageStatusParams) (Cage, error) {
//				panic("mock out the UpdateCageStatus method")
//			},
//			UpdateCageStatusByNameFunc: func(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error) {
//				panic("mock out the UpdateCageStatusByName method")
//			},
//			UpsertCageFunc: func(ctx context.Context, arg UpsertCageParams) error {
//				panic("mock out the UpsertCage method")
//			},
//			UpsertDinosaurFunc: func(ctx context.Context, arg UpsertDinosaurParams) error {
//				panic("mock out the UpsertDinosaur method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// DeleteDinosaurFunc mocks the DeleteDinosaur method.
	DeleteDinosaurFunc func(ctx context.Context, id uuid.UUID) error

	// GetCageFunc mocks the GetCage method.
	GetCageFunc func(ctx context.Context, id uuid.UUID) (Cage, error)

	// GetCagesFunc mocks the GetCages method.
	GetCagesFunc func(ctx context.Context) ([]Cage, error)

	// GetDinosaurFunc mocks the GetDinosaur method.
	GetDinosaurFunc func(ctx context.Context, id uuid.UUID) (Dinosaur, error)

	// GetDinosaurByNameFunc mocks the GetDinosaurByName method.
	GetDinosaurByNameFunc func(ctx context.Context, name sql.NullString) (Dinosaur, error)

	// GetDinosaursFunc mocks the GetDinosaurs method.
	GetDinosaursFunc func(ctx context.Context) ([]Dinosaur, error)

	// GetDinosaursByCageFunc mocks the GetDinosaursByCage method.
	GetDinosaursByCageFunc func(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error)

	// UpdateCageStatusFunc mocks the UpdateCageStatus method.
	UpdateCageStatusFunc func(ctx context.Context, arg UpdateCageStatusParams) (Cage, error)

	// UpdateCageStatusByNameFunc mocks the UpdateCageStatusByName method.
	UpdateCageStatusByNameFunc func(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error)

	// UpsertCageFunc mocks the UpsertCage method.
	UpsertCageFunc func(ctx context.Context, arg UpsertCageParams) error

	// UpsertDinosaurFunc mocks the UpsertDinosaur method.
	UpsertDinosaurFunc func(ctx context.Context, arg UpsertDinosaurParams) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteDinosaur holds details about calls to the DeleteDinosaur method.
		DeleteDinosaur []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetCage holds details about calls to the GetCage method.
		GetCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetCages holds details about calls to the GetCages method.
		GetCages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetDinosaur holds details about calls to the GetDinosaur method.
		GetDinosaur []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetDinosaurByName holds details about calls to the GetDinosaurByName method.
		GetDinosaurByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name sql.NullString
		}
		// GetDinosaurs holds details about calls to the GetDinosaurs method.
		GetDinosaurs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetDinosaursByCage holds details about calls to the GetDinosaursByCage method.
		GetDinosaursByCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CageID is the cageID argument value.
			CageID uuid.NullUUID
		}
		// UpdateCageStatus holds details about calls to the UpdateCageStatus method.
		UpdateCageStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpdateCageStatusParams
		}
		// UpdateCageStatusByName holds details about calls to the UpdateCageStatusByName method.
		UpdateCageStatusByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpdateCageStatusByNameParams
		}
		// UpsertCage holds details about calls to the UpsertCage method.
		UpsertCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpsertCageParams
		}
		// UpsertDinosaur holds details about calls to the UpsertDinosaur method.
		UpsertDinosaur []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpsertDinosaurParams
		}
	}
	lockDeleteDinosaur         sync.RWMutex
	lockGetCage                sync.RWMutex
	lockGetCages               sync.RWMutex
	lockGetDinosaur            sync.RWMutex
	lockGetDinosaurByName      sync.RWMutex
	lockGetDinosaurs           sync.RWMutex
	lockGetDinosaursByCage     sync.RWMutex
	lockUpdateCageStatus       sync.RWMutex
	lockUpdateCageStatusByName sync.RWMutex
	lockUpsertCage             sync.RWMutex
	lockUpsertDinosaur         sync.RWMutex
}

// DeleteDinosaur calls DeleteDinosaurFunc.
func (mock *QuerierMock) DeleteDinosaur(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteDinosaurFunc == nil {
		panic("QuerierMock.DeleteDinosaurFunc: method is nil but Querier.DeleteDinosaur was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteDinosaur.Lock()
	mock.calls.DeleteDinosaur = append(mock.calls.DeleteDinosaur, callInfo)
	mock.lockDeleteDinosaur.Unlock()
	return mock.DeleteDinosaurFunc(ctx, id)
}

// DeleteDinosaurCalls gets all the calls that were made to DeleteDinosaur.
// Check the length with:
//
//	len(mockedQuerier.DeleteDinosaurCalls())
func (mock *QuerierMock) DeleteDinosaurCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteDinosaur.RLock()
	calls = mock.calls.DeleteDinosaur
	mock.lockDeleteDinosaur.RUnlock()
	return calls
}

// GetCage calls GetCageFunc.
func (mock *QuerierMock) GetCage(ctx context.Context, id uuid.UUID) (Cage, error) {
	if mock.GetCageFunc == nil {
		panic("QuerierMock.GetCageFunc: method is nil but Querier.GetCage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetCage.Lock()
	mock.calls.GetCage = append(mock.calls.GetCage, callInfo)
	mock.lockGetCage.Unlock()
	return mock.GetCageFunc(ctx, id)
}

// GetCageCalls gets all the calls that were made to GetCage.
// Check the length with:
//
//	len(mockedQuerier.GetCageCalls())
func (mock *QuerierMock) GetCageCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetCage.RLock()
	calls = mock.calls.GetCage
	mock.lockGetCage.RUnlock()
	return calls
}

// GetCages calls GetCagesFunc.
func (mock *QuerierMock) GetCages(ctx context.Context) ([]Cage, error) {
	if mock.GetCagesFunc == nil {
		panic("QuerierMock.GetCagesFunc: method is nil but Querier.GetCages was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetCages.Lock()
	mock.calls.GetCages = append(mock.calls.GetCages, callInfo)
	mock.lockGetCages.Unlock()
	return mock.GetCagesFunc(ctx)
}

// GetCagesCalls gets all the calls that were made to GetCages.
// Check the length with:
//
//	len(mockedQuerier.GetCagesCalls())
func (mock *QuerierMock) GetCagesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetCages.RLock()
	calls = mock.calls.GetCages
	mock.lockGetCages.RUnlock()
	return calls
}

// GetDinosaur calls GetDinosaurFunc.
func (mock *QuerierMock) GetDinosaur(ctx context.Context, id uuid.UUID) (Dinosaur, error) {
	if mock.GetDinosaurFunc == nil {
		panic("QuerierMock.GetDinosaurFunc: method is nil but Querier.GetDinosaur was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetDinosaur.Lock()
	mock.calls.GetDinosaur = append(mock.calls.GetDinosaur, callInfo)
	mock.lockGetDinosaur.Unlock()
	return mock.GetDinosaurFunc(ctx, id)
}

// GetDinosaurCalls gets all the calls that were made to GetDinosaur.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaurCalls())
func (mock *QuerierMock) GetDinosaurCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetDinosaur.RLock()
	calls = mock.calls.GetDinosaur
	mock.lockGetDinosaur.RUnlock()
	return calls
}

// GetDinosaurByName calls GetDinosaurByNameFunc.
func (mock *QuerierMock) GetDinosaurByName(ctx context.Context, name sql.NullString) (Dinosaur, error) {
	if mock.GetDinosaurByNameFunc == nil {
		panic("QuerierMock.GetDinosaurByNameFunc: method is nil but Querier.GetDinosaurByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name sql.NullString
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetDinosaurByName.Lock()
	mock.calls.GetDinosaurByName = append(mock.calls.GetDinosaurByName, callInfo)
	mock.lockGetDinosaurByName.Unlock()
	return mock.GetDinosaurByNameFunc(ctx, name)
}

// GetDinosaurByNameCalls gets all the calls that were made to GetDinosaurByName.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaurByNameCalls())
func (mock *QuerierMock) GetDinosaurByNameCalls() []struct {
	Ctx  context.Context
	Name sql.NullString
} {
	var calls []struct {
		Ctx  context.Context
		Name sql.NullString
	}
	mock.lockGetDinosaurByName.RLock()
	calls = mock.calls.GetDinosaurByName
	mock.lockGetDinosaurByName.RUnlock()
	return calls
}

// GetDinosaurs calls GetDinosaursFunc.
func (mock *QuerierMock) GetDinosaurs(ctx context.Context) ([]Dinosaur, error) {
	if mock.GetDinosaursFunc == nil {
		panic("QuerierMock.GetDinosaursFunc: method is nil but Querier.GetDinosaurs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetDinosaurs.Lock()
	mock.calls.GetDinosaurs = append(mock.calls.GetDinosaurs, callInfo)
	mock.lockGetDinosaurs.Unlock()
	return mock.GetDinosaursFunc(ctx)
}

// GetDinosaursCalls gets all the calls that were made to GetDinosaurs.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaursCalls())
func (mock *QuerierMock) GetDinosaursCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetDinosaurs.RLock()
	calls = mock.calls.GetDinosaurs
	mock.lockGetDinosaurs.RUnlock()
	return calls
}

// GetDinosaursByCage calls GetDinosaursByCageFunc.
func (mock *QuerierMock) GetDinosaursByCage(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error) {
	if mock.GetDinosaursByCageFunc == nil {
		panic("QuerierMock.GetDinosaursByCageFunc: method is nil but Querier.GetDinosaursByCage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		CageID uuid.NullUUID
	}{
		Ctx:    ctx,
		CageID: cageID,
	}
	mock.lockGetDinosaursByCage.Lock()
	mock.calls.GetDinosaursByCage = append(mock.calls.GetDinosaursByCage, callInfo)
	mock.lockGetDinosaursByCage.Unlock()
	return mock.GetDinosaursByCageFunc(ctx, cageID)
}

// GetDinosaursByCageCalls gets all the calls that were made to GetDinosaursByCage.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaursByCageCalls())
func (mock *QuerierMock) GetDinosaursByCageCalls() []struct {
	Ctx    context.Context
	CageID uuid.NullUUID
} {
	var calls []struct {
		Ctx    context.Context
		CageID uuid.NullUUID
	}
	mock.lockGetDinosaursByCage.RLock()
	calls = mock.calls.GetDinosaursByCage
	mock.lockGetDinosaursByCage.RUnlock()
	return calls
}

// UpdateCageStatus calls UpdateCageStatusFunc.
func (mock *QuerierMock) UpdateCageStatus(ctx context.Context, arg UpdateCageStatusParams) (Cage, error) {
	if mock.UpdateCageStatusFunc == nil {
		panic("QuerierMock.UpdateCageStatusFunc: method is nil but Querier.UpdateCageStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpdateCageStatusParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateCageStatus.Lock()
	mock.calls.UpdateCageStatus = append(mock.calls.UpdateCageStatus, callInfo)
	mock.lockUpdateCageStatus.Unlock()
	return mock.UpdateCageStatusFunc(ctx, arg)
}

// UpdateCageStatusCalls gets all the calls that were made to UpdateCageStatus.
// Check the length with:
//
//	len(mockedQuerier.UpdateCageStatusCalls())
func (mock *QuerierMock) UpdateCageStatusCalls() []struct {
	Ctx context.Context
	Arg UpdateCageStatusParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpdateCageStatusParams
	}
	mock.lockUpdateCageStatus.RLock()
	calls = mock.calls.UpdateCageStatus
	mock.lockUpdateCageStatus.RUnlock()
	return calls
}

// UpdateCageStatusByName calls UpdateCageStatusByNameFunc.
func (mock *QuerierMock) UpdateCageStatusByName(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error) {
	if mock.UpdateCageStatusByNameFunc == nil {
		panic("QuerierMock.UpdateCageStatusByNameFunc: method is nil but Querier.UpdateCageStatusByName was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpdateCageStatusByNameParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateCageStatusByName.Lock()
	mock.calls.UpdateCageStatusByName = append(mock.calls.UpdateCageStatusByName, callInfo)
	mock.lockUpdateCageStatusByName.Unlock()
	return mock.UpdateCageStatusByNameFunc(ctx, arg)
}

// UpdateCageStatusByNameCalls gets all the calls that were made to UpdateCageStatusByName.
// Check the length with:
//
//	len(mockedQuerier.UpdateCageStatusByNameCalls())
func (mock *QuerierMock) UpdateCageStatusByNameCalls() []struct {
	Ctx context.Context
	Arg UpdateCageStatusByNameParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpdateCageStatusByNameParams
	}
	mock.lockUpdateCageStatusByName.RLock()
	calls = mock.calls.UpdateCageStatusByName
	mock.lockUpdateCageStatusByName.RUnlock()
	return calls
}

// UpsertCage calls UpsertCageFunc.
func (mock *QuerierMock) UpsertCage(ctx context.Context, arg UpsertCageParams) error {
	if mock.UpsertCageFunc == nil {
		panic("QuerierMock.UpsertCageFunc: method is nil but Querier.UpsertCage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpsertCageParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCage.Lock()
	mock.calls.UpsertCage = append(mock.calls.UpsertCage, callInfo)
	mock.lockUpsertCage.Unlock()
	return mock.UpsertCageFunc(ctx, arg)
}

// UpsertCageCalls gets all the calls that were made to UpsertCage.
// Check the length with:
//
//	len(mockedQuerier.UpsertCageCalls())
func (mock *QuerierMock) UpsertCageCalls() []struct {
	Ctx context.Context
	Arg UpsertCageParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpsertCageParams
	}
	mock.lockUpsertCage.RLock()
	calls = mock.calls.UpsertCage
	mock.lockUpsertCage.RUnlock()
	return calls
}

// UpsertDinosaur calls UpsertDinosaurFunc.
func (mock *QuerierMock) UpsertDinosaur(ctx context.Context, arg UpsertDinosaurParams) error {
	if mock.UpsertDinosaurFunc == nil {
		panic("QuerierMock.UpsertDinosaurFunc: method is nil but Querier.UpsertDinosaur was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpsertDinosaurParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertDinosaur.Lock()
	mock.calls.UpsertDinosaur = append(mock.calls.UpsertDinosaur, callInfo)
	mock.lockUpsertDinosaur.Unlock()
	return mock.UpsertDinosaurFunc(ctx, arg)
}

// UpsertDinosaurCalls gets all the calls that were made to UpsertDinosaur.
// Check the length with:
//
//	len(mockedQuerier.UpsertDinosaurCalls())
func (mock *QuerierMock) UpsertDinosaurCalls() []struct {
	Ctx context.Context
	Arg UpsertDinosaurParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpsertDinosaurParams
	}
	mock.lockUpsertDinosaur.RLock()
	calls = mock.calls.UpsertDinosaur
	mock.lockUpsertDinosaur.RUnlock()
	return calls
}
