// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package postgres

import (
	"context"
	"database/sql"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			DeleteDinosaurFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteDinosaur method")
//			},
//			GetCageFunc: func(ctx context.Context, id uuid.UUID) (Cage, error) {
//				panic("mock out the GetCage method")
//			},
//			GetCageAndDinosaursFunc: func(ctx context.Context, id uuid.UUID) (GetCageAndDinosaursRow, error) {
//				panic("mock out the GetCageAndDinosaurs method")
//			},
//			GetCageDinosaurCountFunc: func(ctx context.Context, cageID uuid.NullUUID) (int64, error) {
//				panic("mock out the GetCageDinosaurCount method")
//			},
//			GetCagesFunc: func(ctx context.Context) ([]Cage, error) {
//				panic("mock out the GetCages method")
//			},
//			GetCagesByStatusFunc: func(ctx context.Context, status sql.NullInt32) ([]Cage, error) {
//				panic("mock out the GetCagesByStatus method")
//			},
//			GetDinosaurFunc: func(ctx context.Context, id uuid.UUID) (Dinosaur, error) {
//				panic("mock out the GetDinosaur method")
//			},
//			GetDinosaurAndCageFunc: func(ctx context.Context, id uuid.UUID) (GetDinosaurAndCageRow, error) {
//				panic("mock out the GetDinosaurAndCage method")
//			},
//			GetDinosaurByNameFunc: func(ctx context.Context, name sql.NullString) (Dinosaur, error) {
//				panic("mock out the GetDinosaurByName method")
//			},
//			GetDinosaursFunc: func(ctx context.Context) ([]Dinosaur, error) {
//				panic("mock out the GetDinosaurs method")
//			},
//			GetDinosaursByCageFunc: func(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error) {
//				panic("mock out the GetDinosaursByCage method")
//			},
//			GetDinosaursBySpeciesFunc: func(ctx context.Context, species sql.NullInt32) ([]Dinosaur, error) {
//				panic("mock out the GetDinosaursBySpecies method")
//			},
//			UpdateCagePredominateEatingHabitFunc: func(ctx context.Context, arg UpdateCagePredominateEatingHabitParams) error {
//				panic("mock out the UpdateCagePredominateEatingHabit method")
//			},
//			UpdateCageStatusFunc: func(ctx context.Context, arg UpdateCageStatusParams) (Cage, error) {
//				panic("mock out the UpdateCageStatus method")
//			},
//			UpdateCageStatusByNameFunc: func(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error) {
//				panic("mock out the UpdateCageStatusByName method")
//			},
//			UpdateDinosaurCageFunc: func(ctx context.Context, arg UpdateDinosaurCageParams) (Dinosaur, error) {
//				panic("mock out the UpdateDinosaurCage method")
//			},
//			UpsertCageFunc: func(ctx context.Context, arg UpsertCageParams) (Cage, error) {
//				panic("mock out the UpsertCage method")
//			},
//			UpsertDinosaurFunc: func(ctx context.Context, arg UpsertDinosaurParams) (Dinosaur, error) {
//				panic("mock out the UpsertDinosaur method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// DeleteDinosaurFunc mocks the DeleteDinosaur method.
	DeleteDinosaurFunc func(ctx context.Context, id uuid.UUID) error

	// GetCageFunc mocks the GetCage method.
	GetCageFunc func(ctx context.Context, id uuid.UUID) (Cage, error)

	// GetCageAndDinosaursFunc mocks the GetCageAndDinosaurs method.
	GetCageAndDinosaursFunc func(ctx context.Context, id uuid.UUID) (GetCageAndDinosaursRow, error)

	// GetCageDinosaurCountFunc mocks the GetCageDinosaurCount method.
	GetCageDinosaurCountFunc func(ctx context.Context, cageID uuid.NullUUID) (int64, error)

	// GetCagesFunc mocks the GetCages method.
	GetCagesFunc func(ctx context.Context) ([]Cage, error)

	// GetCagesByStatusFunc mocks the GetCagesByStatus method.
	GetCagesByStatusFunc func(ctx context.Context, status sql.NullInt32) ([]Cage, error)

	// GetDinosaurFunc mocks the GetDinosaur method.
	GetDinosaurFunc func(ctx context.Context, id uuid.UUID) (Dinosaur, error)

	// GetDinosaurAndCageFunc mocks the GetDinosaurAndCage method.
	GetDinosaurAndCageFunc func(ctx context.Context, id uuid.UUID) (GetDinosaurAndCageRow, error)

	// GetDinosaurByNameFunc mocks the GetDinosaurByName method.
	GetDinosaurByNameFunc func(ctx context.Context, name sql.NullString) (Dinosaur, error)

	// GetDinosaursFunc mocks the GetDinosaurs method.
	GetDinosaursFunc func(ctx context.Context) ([]Dinosaur, error)

	// GetDinosaursByCageFunc mocks the GetDinosaursByCage method.
	GetDinosaursByCageFunc func(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error)

	// GetDinosaursBySpeciesFunc mocks the GetDinosaursBySpecies method.
	GetDinosaursBySpeciesFunc func(ctx context.Context, species sql.NullInt32) ([]Dinosaur, error)

	// UpdateCagePredominateEatingHabitFunc mocks the UpdateCagePredominateEatingHabit method.
	UpdateCagePredominateEatingHabitFunc func(ctx context.Context, arg UpdateCagePredominateEatingHabitParams) error

	// UpdateCageStatusFunc mocks the UpdateCageStatus method.
	UpdateCageStatusFunc func(ctx context.Context, arg UpdateCageStatusParams) (Cage, error)

	// UpdateCageStatusByNameFunc mocks the UpdateCageStatusByName method.
	UpdateCageStatusByNameFunc func(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error)

	// UpdateDinosaurCageFunc mocks the UpdateDinosaurCage method.
	UpdateDinosaurCageFunc func(ctx context.Context, arg UpdateDinosaurCageParams) (Dinosaur, error)

	// UpsertCageFunc mocks the UpsertCage method.
	UpsertCageFunc func(ctx context.Context, arg UpsertCageParams) (Cage, error)

	// UpsertDinosaurFunc mocks the UpsertDinosaur method.
	UpsertDinosaurFunc func(ctx context.Context, arg UpsertDinosaurParams) (Dinosaur, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteDinosaur holds details about calls to the DeleteDinosaur method.
		DeleteDinosaur []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetCage holds details about calls to the GetCage method.
		GetCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetCageAndDinosaurs holds details about calls to the GetCageAndDinosaurs method.
		GetCageAndDinosaurs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetCageDinosaurCount holds details about calls to the GetCageDinosaurCount method.
		GetCageDinosaurCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CageID is the cageID argument value.
			CageID uuid.NullUUID
		}
		// GetCages holds details about calls to the GetCages method.
		GetCages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetCagesByStatus holds details about calls to the GetCagesByStatus method.
		GetCagesByStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status sql.NullInt32
		}
		// GetDinosaur holds details about calls to the GetDinosaur method.
		GetDinosaur []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetDinosaurAndCage holds details about calls to the GetDinosaurAndCage method.
		GetDinosaurAndCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetDinosaurByName holds details about calls to the GetDinosaurByName method.
		GetDinosaurByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name sql.NullString
		}
		// GetDinosaurs holds details about calls to the GetDinosaurs method.
		GetDinosaurs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetDinosaursByCage holds details about calls to the GetDinosaursByCage method.
		GetDinosaursByCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CageID is the cageID argument value.
			CageID uuid.NullUUID
		}
		// GetDinosaursBySpecies holds details about calls to the GetDinosaursBySpecies method.
		GetDinosaursBySpecies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Species is the species argument value.
			Species sql.NullInt32
		}
		// UpdateCagePredominateEatingHabit holds details about calls to the UpdateCagePredominateEatingHabit method.
		UpdateCagePredominateEatingHabit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpdateCagePredominateEatingHabitParams
		}
		// UpdateCageStatus holds details about calls to the UpdateCageStatus method.
		UpdateCageStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpdateCageStatusParams
		}
		// UpdateCageStatusByName holds details about calls to the UpdateCageStatusByName method.
		UpdateCageStatusByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpdateCageStatusByNameParams
		}
		// UpdateDinosaurCage holds details about calls to the UpdateDinosaurCage method.
		UpdateDinosaurCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpdateDinosaurCageParams
		}
		// UpsertCage holds details about calls to the UpsertCage method.
		UpsertCage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpsertCageParams
		}
		// UpsertDinosaur holds details about calls to the UpsertDinosaur method.
		UpsertDinosaur []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpsertDinosaurParams
		}
	}
	lockDeleteDinosaur                   sync.RWMutex
	lockGetCage                          sync.RWMutex
	lockGetCageAndDinosaurs              sync.RWMutex
	lockGetCageDinosaurCount             sync.RWMutex
	lockGetCages                         sync.RWMutex
	lockGetCagesByStatus                 sync.RWMutex
	lockGetDinosaur                      sync.RWMutex
	lockGetDinosaurAndCage               sync.RWMutex
	lockGetDinosaurByName                sync.RWMutex
	lockGetDinosaurs                     sync.RWMutex
	lockGetDinosaursByCage               sync.RWMutex
	lockGetDinosaursBySpecies            sync.RWMutex
	lockUpdateCagePredominateEatingHabit sync.RWMutex
	lockUpdateCageStatus                 sync.RWMutex
	lockUpdateCageStatusByName           sync.RWMutex
	lockUpdateDinosaurCage               sync.RWMutex
	lockUpsertCage                       sync.RWMutex
	lockUpsertDinosaur                   sync.RWMutex
}

// DeleteDinosaur calls DeleteDinosaurFunc.
func (mock *QuerierMock) DeleteDinosaur(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteDinosaurFunc == nil {
		panic("QuerierMock.DeleteDinosaurFunc: method is nil but Querier.DeleteDinosaur was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteDinosaur.Lock()
	mock.calls.DeleteDinosaur = append(mock.calls.DeleteDinosaur, callInfo)
	mock.lockDeleteDinosaur.Unlock()
	return mock.DeleteDinosaurFunc(ctx, id)
}

// DeleteDinosaurCalls gets all the calls that were made to DeleteDinosaur.
// Check the length with:
//
//	len(mockedQuerier.DeleteDinosaurCalls())
func (mock *QuerierMock) DeleteDinosaurCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteDinosaur.RLock()
	calls = mock.calls.DeleteDinosaur
	mock.lockDeleteDinosaur.RUnlock()
	return calls
}

// GetCage calls GetCageFunc.
func (mock *QuerierMock) GetCage(ctx context.Context, id uuid.UUID) (Cage, error) {
	if mock.GetCageFunc == nil {
		panic("QuerierMock.GetCageFunc: method is nil but Querier.GetCage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetCage.Lock()
	mock.calls.GetCage = append(mock.calls.GetCage, callInfo)
	mock.lockGetCage.Unlock()
	return mock.GetCageFunc(ctx, id)
}

// GetCageCalls gets all the calls that were made to GetCage.
// Check the length with:
//
//	len(mockedQuerier.GetCageCalls())
func (mock *QuerierMock) GetCageCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetCage.RLock()
	calls = mock.calls.GetCage
	mock.lockGetCage.RUnlock()
	return calls
}

// GetCageAndDinosaurs calls GetCageAndDinosaursFunc.
func (mock *QuerierMock) GetCageAndDinosaurs(ctx context.Context, id uuid.UUID) (GetCageAndDinosaursRow, error) {
	if mock.GetCageAndDinosaursFunc == nil {
		panic("QuerierMock.GetCageAndDinosaursFunc: method is nil but Querier.GetCageAndDinosaurs was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetCageAndDinosaurs.Lock()
	mock.calls.GetCageAndDinosaurs = append(mock.calls.GetCageAndDinosaurs, callInfo)
	mock.lockGetCageAndDinosaurs.Unlock()
	return mock.GetCageAndDinosaursFunc(ctx, id)
}

// GetCageAndDinosaursCalls gets all the calls that were made to GetCageAndDinosaurs.
// Check the length with:
//
//	len(mockedQuerier.GetCageAndDinosaursCalls())
func (mock *QuerierMock) GetCageAndDinosaursCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetCageAndDinosaurs.RLock()
	calls = mock.calls.GetCageAndDinosaurs
	mock.lockGetCageAndDinosaurs.RUnlock()
	return calls
}

// GetCageDinosaurCount calls GetCageDinosaurCountFunc.
func (mock *QuerierMock) GetCageDinosaurCount(ctx context.Context, cageID uuid.NullUUID) (int64, error) {
	if mock.GetCageDinosaurCountFunc == nil {
		panic("QuerierMock.GetCageDinosaurCountFunc: method is nil but Querier.GetCageDinosaurCount was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		CageID uuid.NullUUID
	}{
		Ctx:    ctx,
		CageID: cageID,
	}
	mock.lockGetCageDinosaurCount.Lock()
	mock.calls.GetCageDinosaurCount = append(mock.calls.GetCageDinosaurCount, callInfo)
	mock.lockGetCageDinosaurCount.Unlock()
	return mock.GetCageDinosaurCountFunc(ctx, cageID)
}

// GetCageDinosaurCountCalls gets all the calls that were made to GetCageDinosaurCount.
// Check the length with:
//
//	len(mockedQuerier.GetCageDinosaurCountCalls())
func (mock *QuerierMock) GetCageDinosaurCountCalls() []struct {
	Ctx    context.Context
	CageID uuid.NullUUID
} {
	var calls []struct {
		Ctx    context.Context
		CageID uuid.NullUUID
	}
	mock.lockGetCageDinosaurCount.RLock()
	calls = mock.calls.GetCageDinosaurCount
	mock.lockGetCageDinosaurCount.RUnlock()
	return calls
}

// GetCages calls GetCagesFunc.
func (mock *QuerierMock) GetCages(ctx context.Context) ([]Cage, error) {
	if mock.GetCagesFunc == nil {
		panic("QuerierMock.GetCagesFunc: method is nil but Querier.GetCages was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetCages.Lock()
	mock.calls.GetCages = append(mock.calls.GetCages, callInfo)
	mock.lockGetCages.Unlock()
	return mock.GetCagesFunc(ctx)
}

// GetCagesCalls gets all the calls that were made to GetCages.
// Check the length with:
//
//	len(mockedQuerier.GetCagesCalls())
func (mock *QuerierMock) GetCagesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetCages.RLock()
	calls = mock.calls.GetCages
	mock.lockGetCages.RUnlock()
	return calls
}

// GetCagesByStatus calls GetCagesByStatusFunc.
func (mock *QuerierMock) GetCagesByStatus(ctx context.Context, status sql.NullInt32) ([]Cage, error) {
	if mock.GetCagesByStatusFunc == nil {
		panic("QuerierMock.GetCagesByStatusFunc: method is nil but Querier.GetCagesByStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status sql.NullInt32
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockGetCagesByStatus.Lock()
	mock.calls.GetCagesByStatus = append(mock.calls.GetCagesByStatus, callInfo)
	mock.lockGetCagesByStatus.Unlock()
	return mock.GetCagesByStatusFunc(ctx, status)
}

// GetCagesByStatusCalls gets all the calls that were made to GetCagesByStatus.
// Check the length with:
//
//	len(mockedQuerier.GetCagesByStatusCalls())
func (mock *QuerierMock) GetCagesByStatusCalls() []struct {
	Ctx    context.Context
	Status sql.NullInt32
} {
	var calls []struct {
		Ctx    context.Context
		Status sql.NullInt32
	}
	mock.lockGetCagesByStatus.RLock()
	calls = mock.calls.GetCagesByStatus
	mock.lockGetCagesByStatus.RUnlock()
	return calls
}

// GetDinosaur calls GetDinosaurFunc.
func (mock *QuerierMock) GetDinosaur(ctx context.Context, id uuid.UUID) (Dinosaur, error) {
	if mock.GetDinosaurFunc == nil {
		panic("QuerierMock.GetDinosaurFunc: method is nil but Querier.GetDinosaur was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetDinosaur.Lock()
	mock.calls.GetDinosaur = append(mock.calls.GetDinosaur, callInfo)
	mock.lockGetDinosaur.Unlock()
	return mock.GetDinosaurFunc(ctx, id)
}

// GetDinosaurCalls gets all the calls that were made to GetDinosaur.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaurCalls())
func (mock *QuerierMock) GetDinosaurCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetDinosaur.RLock()
	calls = mock.calls.GetDinosaur
	mock.lockGetDinosaur.RUnlock()
	return calls
}

// GetDinosaurAndCage calls GetDinosaurAndCageFunc.
func (mock *QuerierMock) GetDinosaurAndCage(ctx context.Context, id uuid.UUID) (GetDinosaurAndCageRow, error) {
	if mock.GetDinosaurAndCageFunc == nil {
		panic("QuerierMock.GetDinosaurAndCageFunc: method is nil but Querier.GetDinosaurAndCage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetDinosaurAndCage.Lock()
	mock.calls.GetDinosaurAndCage = append(mock.calls.GetDinosaurAndCage, callInfo)
	mock.lockGetDinosaurAndCage.Unlock()
	return mock.GetDinosaurAndCageFunc(ctx, id)
}

// GetDinosaurAndCageCalls gets all the calls that were made to GetDinosaurAndCage.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaurAndCageCalls())
func (mock *QuerierMock) GetDinosaurAndCageCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetDinosaurAndCage.RLock()
	calls = mock.calls.GetDinosaurAndCage
	mock.lockGetDinosaurAndCage.RUnlock()
	return calls
}

// GetDinosaurByName calls GetDinosaurByNameFunc.
func (mock *QuerierMock) GetDinosaurByName(ctx context.Context, name sql.NullString) (Dinosaur, error) {
	if mock.GetDinosaurByNameFunc == nil {
		panic("QuerierMock.GetDinosaurByNameFunc: method is nil but Querier.GetDinosaurByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name sql.NullString
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetDinosaurByName.Lock()
	mock.calls.GetDinosaurByName = append(mock.calls.GetDinosaurByName, callInfo)
	mock.lockGetDinosaurByName.Unlock()
	return mock.GetDinosaurByNameFunc(ctx, name)
}

// GetDinosaurByNameCalls gets all the calls that were made to GetDinosaurByName.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaurByNameCalls())
func (mock *QuerierMock) GetDinosaurByNameCalls() []struct {
	Ctx  context.Context
	Name sql.NullString
} {
	var calls []struct {
		Ctx  context.Context
		Name sql.NullString
	}
	mock.lockGetDinosaurByName.RLock()
	calls = mock.calls.GetDinosaurByName
	mock.lockGetDinosaurByName.RUnlock()
	return calls
}

// GetDinosaurs calls GetDinosaursFunc.
func (mock *QuerierMock) GetDinosaurs(ctx context.Context) ([]Dinosaur, error) {
	if mock.GetDinosaursFunc == nil {
		panic("QuerierMock.GetDinosaursFunc: method is nil but Querier.GetDinosaurs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetDinosaurs.Lock()
	mock.calls.GetDinosaurs = append(mock.calls.GetDinosaurs, callInfo)
	mock.lockGetDinosaurs.Unlock()
	return mock.GetDinosaursFunc(ctx)
}

// GetDinosaursCalls gets all the calls that were made to GetDinosaurs.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaursCalls())
func (mock *QuerierMock) GetDinosaursCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetDinosaurs.RLock()
	calls = mock.calls.GetDinosaurs
	mock.lockGetDinosaurs.RUnlock()
	return calls
}

// GetDinosaursByCage calls GetDinosaursByCageFunc.
func (mock *QuerierMock) GetDinosaursByCage(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error) {
	if mock.GetDinosaursByCageFunc == nil {
		panic("QuerierMock.GetDinosaursByCageFunc: method is nil but Querier.GetDinosaursByCage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		CageID uuid.NullUUID
	}{
		Ctx:    ctx,
		CageID: cageID,
	}
	mock.lockGetDinosaursByCage.Lock()
	mock.calls.GetDinosaursByCage = append(mock.calls.GetDinosaursByCage, callInfo)
	mock.lockGetDinosaursByCage.Unlock()
	return mock.GetDinosaursByCageFunc(ctx, cageID)
}

// GetDinosaursByCageCalls gets all the calls that were made to GetDinosaursByCage.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaursByCageCalls())
func (mock *QuerierMock) GetDinosaursByCageCalls() []struct {
	Ctx    context.Context
	CageID uuid.NullUUID
} {
	var calls []struct {
		Ctx    context.Context
		CageID uuid.NullUUID
	}
	mock.lockGetDinosaursByCage.RLock()
	calls = mock.calls.GetDinosaursByCage
	mock.lockGetDinosaursByCage.RUnlock()
	return calls
}

// GetDinosaursBySpecies calls GetDinosaursBySpeciesFunc.
func (mock *QuerierMock) GetDinosaursBySpecies(ctx context.Context, species sql.NullInt32) ([]Dinosaur, error) {
	if mock.GetDinosaursBySpeciesFunc == nil {
		panic("QuerierMock.GetDinosaursBySpeciesFunc: method is nil but Querier.GetDinosaursBySpecies was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Species sql.NullInt32
	}{
		Ctx:     ctx,
		Species: species,
	}
	mock.lockGetDinosaursBySpecies.Lock()
	mock.calls.GetDinosaursBySpecies = append(mock.calls.GetDinosaursBySpecies, callInfo)
	mock.lockGetDinosaursBySpecies.Unlock()
	return mock.GetDinosaursBySpeciesFunc(ctx, species)
}

// GetDinosaursBySpeciesCalls gets all the calls that were made to GetDinosaursBySpecies.
// Check the length with:
//
//	len(mockedQuerier.GetDinosaursBySpeciesCalls())
func (mock *QuerierMock) GetDinosaursBySpeciesCalls() []struct {
	Ctx     context.Context
	Species sql.NullInt32
} {
	var calls []struct {
		Ctx     context.Context
		Species sql.NullInt32
	}
	mock.lockGetDinosaursBySpecies.RLock()
	calls = mock.calls.GetDinosaursBySpecies
	mock.lockGetDinosaursBySpecies.RUnlock()
	return calls
}

// UpdateCagePredominateEatingHabit calls UpdateCagePredominateEatingHabitFunc.
func (mock *QuerierMock) UpdateCagePredominateEatingHabit(ctx context.Context, arg UpdateCagePredominateEatingHabitParams) error {
	if mock.UpdateCagePredominateEatingHabitFunc == nil {
		panic("QuerierMock.UpdateCagePredominateEatingHabitFunc: method is nil but Querier.UpdateCagePredominateEatingHabit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpdateCagePredominateEatingHabitParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateCagePredominateEatingHabit.Lock()
	mock.calls.UpdateCagePredominateEatingHabit = append(mock.calls.UpdateCagePredominateEatingHabit, callInfo)
	mock.lockUpdateCagePredominateEatingHabit.Unlock()
	return mock.UpdateCagePredominateEatingHabitFunc(ctx, arg)
}

// UpdateCagePredominateEatingHabitCalls gets all the calls that were made to UpdateCagePredominateEatingHabit.
// Check the length with:
//
//	len(mockedQuerier.UpdateCagePredominateEatingHabitCalls())
func (mock *QuerierMock) UpdateCagePredominateEatingHabitCalls() []struct {
	Ctx context.Context
	Arg UpdateCagePredominateEatingHabitParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpdateCagePredominateEatingHabitParams
	}
	mock.lockUpdateCagePredominateEatingHabit.RLock()
	calls = mock.calls.UpdateCagePredominateEatingHabit
	mock.lockUpdateCagePredominateEatingHabit.RUnlock()
	return calls
}

// UpdateCageStatus calls UpdateCageStatusFunc.
func (mock *QuerierMock) UpdateCageStatus(ctx context.Context, arg UpdateCageStatusParams) (Cage, error) {
	if mock.UpdateCageStatusFunc == nil {
		panic("QuerierMock.UpdateCageStatusFunc: method is nil but Querier.UpdateCageStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpdateCageStatusParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateCageStatus.Lock()
	mock.calls.UpdateCageStatus = append(mock.calls.UpdateCageStatus, callInfo)
	mock.lockUpdateCageStatus.Unlock()
	return mock.UpdateCageStatusFunc(ctx, arg)
}

// UpdateCageStatusCalls gets all the calls that were made to UpdateCageStatus.
// Check the length with:
//
//	len(mockedQuerier.UpdateCageStatusCalls())
func (mock *QuerierMock) UpdateCageStatusCalls() []struct {
	Ctx context.Context
	Arg UpdateCageStatusParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpdateCageStatusParams
	}
	mock.lockUpdateCageStatus.RLock()
	calls = mock.calls.UpdateCageStatus
	mock.lockUpdateCageStatus.RUnlock()
	return calls
}

// UpdateCageStatusByName calls UpdateCageStatusByNameFunc.
func (mock *QuerierMock) UpdateCageStatusByName(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error) {
	if mock.UpdateCageStatusByNameFunc == nil {
		panic("QuerierMock.UpdateCageStatusByNameFunc: method is nil but Querier.UpdateCageStatusByName was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpdateCageStatusByNameParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateCageStatusByName.Lock()
	mock.calls.UpdateCageStatusByName = append(mock.calls.UpdateCageStatusByName, callInfo)
	mock.lockUpdateCageStatusByName.Unlock()
	return mock.UpdateCageStatusByNameFunc(ctx, arg)
}

// UpdateCageStatusByNameCalls gets all the calls that were made to UpdateCageStatusByName.
// Check the length with:
//
//	len(mockedQuerier.UpdateCageStatusByNameCalls())
func (mock *QuerierMock) UpdateCageStatusByNameCalls() []struct {
	Ctx context.Context
	Arg UpdateCageStatusByNameParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpdateCageStatusByNameParams
	}
	mock.lockUpdateCageStatusByName.RLock()
	calls = mock.calls.UpdateCageStatusByName
	mock.lockUpdateCageStatusByName.RUnlock()
	return calls
}

// UpdateDinosaurCage calls UpdateDinosaurCageFunc.
func (mock *QuerierMock) UpdateDinosaurCage(ctx context.Context, arg UpdateDinosaurCageParams) (Dinosaur, error) {
	if mock.UpdateDinosaurCageFunc == nil {
		panic("QuerierMock.UpdateDinosaurCageFunc: method is nil but Querier.UpdateDinosaurCage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpdateDinosaurCageParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateDinosaurCage.Lock()
	mock.calls.UpdateDinosaurCage = append(mock.calls.UpdateDinosaurCage, callInfo)
	mock.lockUpdateDinosaurCage.Unlock()
	return mock.UpdateDinosaurCageFunc(ctx, arg)
}

// UpdateDinosaurCageCalls gets all the calls that were made to UpdateDinosaurCage.
// Check the length with:
//
//	len(mockedQuerier.UpdateDinosaurCageCalls())
func (mock *QuerierMock) UpdateDinosaurCageCalls() []struct {
	Ctx context.Context
	Arg UpdateDinosaurCageParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpdateDinosaurCageParams
	}
	mock.lockUpdateDinosaurCage.RLock()
	calls = mock.calls.UpdateDinosaurCage
	mock.lockUpdateDinosaurCage.RUnlock()
	return calls
}

// UpsertCage calls UpsertCageFunc.
func (mock *QuerierMock) UpsertCage(ctx context.Context, arg UpsertCageParams) (Cage, error) {
	if mock.UpsertCageFunc == nil {
		panic("QuerierMock.UpsertCageFunc: method is nil but Querier.UpsertCage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpsertCageParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCage.Lock()
	mock.calls.UpsertCage = append(mock.calls.UpsertCage, callInfo)
	mock.lockUpsertCage.Unlock()
	return mock.UpsertCageFunc(ctx, arg)
}

// UpsertCageCalls gets all the calls that were made to UpsertCage.
// Check the length with:
//
//	len(mockedQuerier.UpsertCageCalls())
func (mock *QuerierMock) UpsertCageCalls() []struct {
	Ctx context.Context
	Arg UpsertCageParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpsertCageParams
	}
	mock.lockUpsertCage.RLock()
	calls = mock.calls.UpsertCage
	mock.lockUpsertCage.RUnlock()
	return calls
}

// UpsertDinosaur calls UpsertDinosaurFunc.
func (mock *QuerierMock) UpsertDinosaur(ctx context.Context, arg UpsertDinosaurParams) (Dinosaur, error) {
	if mock.UpsertDinosaurFunc == nil {
		panic("QuerierMock.UpsertDinosaurFunc: method is nil but Querier.UpsertDinosaur was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpsertDinosaurParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertDinosaur.Lock()
	mock.calls.UpsertDinosaur = append(mock.calls.UpsertDinosaur, callInfo)
	mock.lockUpsertDinosaur.Unlock()
	return mock.UpsertDinosaurFunc(ctx, arg)
}

// UpsertDinosaurCalls gets all the calls that were made to UpsertDinosaur.
// Check the length with:
//
//	len(mockedQuerier.UpsertDinosaurCalls())
func (mock *QuerierMock) UpsertDinosaurCalls() []struct {
	Ctx context.Context
	Arg UpsertDinosaurParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpsertDinosaurParams
	}
	mock.lockUpsertDinosaur.RLock()
	calls = mock.calls.UpsertDinosaur
	mock.lockUpsertDinosaur.RUnlock()
	return calls
}
