// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteDinosaur(ctx context.Context, id uuid.UUID) error
	GetCage(ctx context.Context, id uuid.UUID) (Cage, error)
	GetCages(ctx context.Context) ([]Cage, error)
	GetDinosaur(ctx context.Context, id uuid.UUID) (Dinosaur, error)
	GetDinosaurByName(ctx context.Context, name sql.NullString) (Dinosaur, error)
	GetDinosaurs(ctx context.Context) ([]Dinosaur, error)
	GetDinosaursByCage(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error)
	UpdateCageStatus(ctx context.Context, arg UpdateCageStatusParams) (Cage, error)
	UpdateCageStatusByName(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error)
	UpsertCage(ctx context.Context, arg UpsertCageParams) error
	UpsertDinosaur(ctx context.Context, arg UpsertDinosaurParams) error
}

var _ Querier = (*Queries)(nil)
