// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteDinosaur = `-- name: DeleteDinosaur :exec
DELETE FROM dinosaur WHERE id = $1
`

func (q *Queries) DeleteDinosaur(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDinosaur, id)
	return err
}

const getCage = `-- name: GetCage :one
SELECT id, name, status FROM cage WHERE id = $1
`

func (q *Queries) GetCage(ctx context.Context, id uuid.UUID) (Cage, error) {
	row := q.db.QueryRowContext(ctx, getCage, id)
	var i Cage
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getCages = `-- name: GetCages :many
SELECT id, name, status FROM cage
`

func (q *Queries) GetCages(ctx context.Context) ([]Cage, error) {
	rows, err := q.db.QueryContext(ctx, getCages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cage
	for rows.Next() {
		var i Cage
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDinosaur = `-- name: GetDinosaur :one
SELECT id, name, eating_habit, species, cage_id FROM dinosaur WHERE id = $1
`

func (q *Queries) GetDinosaur(ctx context.Context, id uuid.UUID) (Dinosaur, error) {
	row := q.db.QueryRowContext(ctx, getDinosaur, id)
	var i Dinosaur
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EatingHabit,
		&i.Species,
		&i.CageID,
	)
	return i, err
}

const getDinosaurByName = `-- name: GetDinosaurByName :one
SELECT id, name, eating_habit, species, cage_id FROM dinosaur WHERE name = $1
`

func (q *Queries) GetDinosaurByName(ctx context.Context, name sql.NullString) (Dinosaur, error) {
	row := q.db.QueryRowContext(ctx, getDinosaurByName, name)
	var i Dinosaur
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EatingHabit,
		&i.Species,
		&i.CageID,
	)
	return i, err
}

const getDinosaurs = `-- name: GetDinosaurs :many
SELECT id, name, eating_habit, species, cage_id FROM dinosaur
`

func (q *Queries) GetDinosaurs(ctx context.Context) ([]Dinosaur, error) {
	rows, err := q.db.QueryContext(ctx, getDinosaurs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dinosaur
	for rows.Next() {
		var i Dinosaur
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EatingHabit,
			&i.Species,
			&i.CageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDinosaursByCage = `-- name: GetDinosaursByCage :many
SELECT id, name, eating_habit, species, cage_id FROM dinosaur WHERE cage_id = $1
`

func (q *Queries) GetDinosaursByCage(ctx context.Context, cageID uuid.NullUUID) ([]Dinosaur, error) {
	rows, err := q.db.QueryContext(ctx, getDinosaursByCage, cageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dinosaur
	for rows.Next() {
		var i Dinosaur
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EatingHabit,
			&i.Species,
			&i.CageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCageStatus = `-- name: UpdateCageStatus :one
UPDATE cage SET status = $1 WHERE id = $2 RETURNING id, name, status
`

type UpdateCageStatusParams struct {
	Status sql.NullInt32
	ID     uuid.UUID
}

func (q *Queries) UpdateCageStatus(ctx context.Context, arg UpdateCageStatusParams) (Cage, error) {
	row := q.db.QueryRowContext(ctx, updateCageStatus, arg.Status, arg.ID)
	var i Cage
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const updateCageStatusByName = `-- name: UpdateCageStatusByName :one
UPDATE cage SET status = $1 WHERE name = $2 RETURNING id, name, status
`

type UpdateCageStatusByNameParams struct {
	Status sql.NullInt32
	Name   sql.NullString
}

func (q *Queries) UpdateCageStatusByName(ctx context.Context, arg UpdateCageStatusByNameParams) (Cage, error) {
	row := q.db.QueryRowContext(ctx, updateCageStatusByName, arg.Status, arg.Name)
	var i Cage
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const upsertCage = `-- name: UpsertCage :exec
INSERT INTO cage (name, status) VALUES ($1, $2)
    ON CONFLICT (name) DO UPDATE SET (status) = ($2)
`

type UpsertCageParams struct {
	Name   sql.NullString
	Status sql.NullInt32
}

func (q *Queries) UpsertCage(ctx context.Context, arg UpsertCageParams) error {
	_, err := q.db.ExecContext(ctx, upsertCage, arg.Name, arg.Status)
	return err
}

const upsertDinosaur = `-- name: UpsertDinosaur :exec
INSERT INTO dinosaur (name, eating_habit, species, cage_id)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (name) DO UPDATE SET (eating_habit, species, cage_id) = ($2, $3, $4)
`

type UpsertDinosaurParams struct {
	Name        sql.NullString
	EatingHabit sql.NullInt32
	Species     sql.NullInt32
	CageID      uuid.NullUUID
}

func (q *Queries) UpsertDinosaur(ctx context.Context, arg UpsertDinosaurParams) error {
	_, err := q.db.ExecContext(ctx, upsertDinosaur,
		arg.Name,
		arg.EatingHabit,
		arg.Species,
		arg.CageID,
	)
	return err
}
